# Generated by Django 5.1.6 on 2025-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eurorace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationreport",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
