[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "dj-rest-auth[with-social]>=5.1.0",
    "django-environ>=0.11.2",
    "django-rest-framework>=0.1.0",
    "django>=3.2.25",
    "drf-spectacular[sidecar]>=0.28.0",
]
